spring.application.name=quanlyphongtro

# CẤU HÌNH KẾT NỐI MYSQL LÊN ĐÁM MÂY (AIVEN)
spring.datasource.url=jdbc:mysql://mysql-24a62e2b-cphamquynh087-ee6b.a.aivencloud.com:19892/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_yGDDB1dbZsnMiEq2ZC5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tự động tạo bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cấu hình Gửi Email Tự Động
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cphamquynh087@gmail.com
spring.mail.password=slzm mzma admp vmoy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true